name: Trigger auto deployment for dotnet

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/dotnet-AutoDeployTrigger-4bfc7fbb-5a12-41f6-a593-ffaf9185db96.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerappsrakzj.azurecr.io
          username: ${{ secrets.DOTNET_REGISTRY_USERNAME }}
          password: ${{ secrets.DOTNET_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerappsrakzj.azurecr.io/dotnet:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DOTNET_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n dotnet -g my-container-apps --server containerappsrakzj.azurecr.io --username  ${{ secrets.DOTNET_REGISTRY_USERNAME }} --password ${{ secrets.DOTNET_REGISTRY_PASSWORD }}
            az containerapp update -n dotnet -g my-container-apps --image containerappsrakzj.azurecr.io/dotnet:${{ github.sha }}
